# Dockerfile for Streamlit
FROM python:3.9-slim

WORKDIR /app

COPY app/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .

EXPOSE 8501

CMD ["streamlit", "run", "labeling_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
